export const benefitSchemes = [
    {
      id: "pm-kisan",
      name: "PM-KISAN योजना",
      nameEn: "PM-KISAN Scheme",
      category: "Agriculture",
      amount: "₹6,000/year",
      eligibility: [
        "farmer",
        "agriculture",
        "land owner",
        "rural",
        "किसान",
        "खेती",
      ],
      description: "Direct income support for farmers",
      level: "National",
      icon: "🌾",
    },
    {
      id: "ayushman-bharat",
      name: "आयुष्मान भारत",
      nameEn: "Ayushman Bharat",
      category: "Healthcare",
      amount: "₹5 Lakh coverage",
      eligibility: [
        "poor",
        "healthcare",
        "medical",
        "treatment",
        "hospital",
        "गरीब",
        "इलाज",
      ],
      description: "Health insurance for economically vulnerable families",
      level: "National",
      icon: "🏥",
    },
    {
      id: "pradhan-mantri-awas",
      name: "प्रधानमंत्री आवास योजना",
      nameEn: "PM Awas Yojana",
      category: "Housing",
      amount: "₹2.5 Lakh subsidy",
      eligibility: [
        "house",
        "home",
        "shelter",
        "construction",
        "rural",
        "urban",
        "घर",
        "मकान",
      ],
      description: "Housing for All scheme",
      level: "National",
      icon: "🏠",
    },
    {
      id: "ujjwala",
      name: "उज्ज्वला योजना",
      nameEn: "Ujjwala Yojana",
      category: "Energy",
      amount: "Free LPG connection",
      eligibility: [
        "cooking",
        "gas",
        "women",
        "bpl",
        "below poverty",
        "महिला",
        "गैस",
      ],
      description: "Free LPG connections for BPL families",
      level: "National",
      icon: "🔥",
    },
    {
      id: "mid-day-meal",
      name: "मध्याह्न भोजन योजना",
      nameEn: "Mid Day Meal Scheme",
      category: "Education",
      amount: "Free meals",
      eligibility: [
        "school",
        "children",
        "student",
        "education",
        "nutrition",
        "बच्चे",
        "स्कूल",
      ],
      description: "Nutritious meals for school children",
      level: "National",
      icon: "🍽️",
    },
  ];